Admin pannel
DUT-Info-Montreuil/SAE-Generateur-Dexo pull request #104
Opened 2023-01-14 16:02 UTC by almerion

2023-01-14 16:56 UTC, NaulaN requested changes

2023-01-14 16:56 UTC, NaulaN commented on src/ajax/delete_element.php
> +        $query = deleteImage();
```suggestion
    $query = ($mode == 0) ? deleteAccount() : deleteImage();
```
This is like a boolean condition, you can write this condition with only one line

2023-01-14 16:56 UTC, NaulaN commented on src/modules/mod_admin_panel/cont_admin_panel.php
> +                break;*/
Dirty code for merging into `master` branch

2023-01-14 16:56 UTC, NaulaN commented on src/modules/mod_admin_panel/cont_admin_panel.php
> +        }
```suggestion
        $datas = ($mode == 0) ? $this->model->getAccounts() : $this->model->getImages();
```

2023-01-14 16:56 UTC, NaulaN commented on src/modules/mod_admin_panel/model_admin_panel.php
> +    }*/
Dirty code for merging into `master` branch

2023-01-15 12:39 UTC, almerion commented on src/ajax/delete_element.php
> +        $query = deleteImage();
can have more modes so it should stay with if else

2023-01-15 12:39 UTC, almerion commented on src/modules/mod_admin_panel/cont_admin_panel.php
> +        }
same

2023-01-15 12:45 UTC, NaulaN commented
@almerion good for merging ?

2023-01-15 12:49 UTC, NaulaN approved these changes

2023-01-15 12:49 UTC, merged