Fontionality popin
DUT-Info-Montreuil/SAE-Generateur-Dexo pull request #44
Opened 2022-11-08 18:29 UTC by almerion

2022-11-08 19:42 UTC, NaulaN requested changes

2022-11-08 19:42 UTC, NaulaN commented on src/css/home-page.css
> +#popInInfoDiv {
```suggestion
#pop-in-info-div {
```
or, we needs to change all attributes from `xx-xx` to `xxXx`

2022-11-08 19:42 UTC, NaulaN commented on src/css/home-page.css
> +.popInElement {
Same here

2022-11-08 19:42 UTC, NaulaN commented on src/index.php
> +    <html lang="fr">
Why you change position of `<?php ?>` tags ?

2022-11-08 19:42 UTC, NaulaN commented on src/index.php
> +    <script src="./main.js"></script>
Wrong path, you need to move on `./js/main.js`
```suggestion
    <script src="./js/main.js"></script>
```

2022-11-08 19:42 UTC, NaulaN commented on src/main.js
> +    let div = document.getElementById("popInInfoDiv");
This variable not going to change so let's go change to `const`
```suggestion
    const div = document.getElementById("popInInfoDiv");
```

2022-11-08 19:42 UTC, NaulaN commented on src/js/css_loader.js
> +        } else if (nameVar === 'module' && valueVar === 'home') {
You repeat two times `nameVar === 'module'`

2022-11-08 19:42 UTC, NaulaN commented on src/main.js
> +    let elem = document.createElement("div");
```suggestion
    const elem = document.createElement("div");
```

2022-11-08 19:42 UTC, NaulaN commented on src/main.js
> +    let paragraph = document.createElement("p");
```suggestion
    const paragraph = document.createElement("p");
```

2022-11-08 19:42 UTC, NaulaN commented on src/main.js
> +    if (isPermanent === false) {
```suggestion
    if (!isPermanent) {
```

2022-11-08 19:42 UTC, NaulaN commented on src/modules/mod_user/vue_user.php
> +    <div id="popInInfoDiv" class="test"></div>
bruh, `class="test"`

2022-11-08 19:42 UTC, NaulaN commented on src/modules/mod_user/vue_user.php
> +        </script>
You can create a `.js` file and put your script on it ?

2022-11-09 08:24 UTC, almerion commented on src/index.php
> +    <html lang="fr">
![image](https://user-images.githubusercontent.com/95338528/200777205-054c99eb-0eb5-4933-94ef-8717ac39090b.png)
:moyai:

2022-11-09 08:25 UTC, NaulaN commented on src/index.php
> +    <html lang="fr">
mb

2022-11-09 08:51 UTC, almerion commented on src/modules/mod_user/vue_user.php
> +        </script>
done

2022-11-09 08:51 UTC, almerion commented on src/modules/mod_user/vue_user.php
> +    <div id="popInInfoDiv" class="test"></div>
exact, bruh, i removed it

2022-11-09 09:03 UTC, almerion commented on src/index.php
> +    <script src="./main.js"></script>
fixed

2022-11-09 09:03 UTC, almerion commented on src/css/home-page.css
> +.popInElement {
adopted the kebab-case

2022-11-09 09:04 UTC, almerion commented on src/css/home-page.css
> +#popInInfoDiv {
Adopted the kebab-case

2022-11-09 09:17 UTC, NaulaN requested changes

2022-11-09 09:18 UTC, almerion commented on src/js/css_loader.js
> +            if ( valueVar == "user") {
it's because of Joe

2022-11-09 09:19 UTC, NaulaN approved these changes

2022-11-09 09:19 UTC, almerion commented on src/js/css_loader.js
> +            if ( valueVar == "user") {
Joe mama

2022-11-09 09:19 UTC, merged